services:
  smct-mailer:
    build:
      context: ./
      dockerfile: Dockerfile
    image: smct-mailer
    container_name: smct-mailer
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - /home/webserver/systems/testing/Multiple-Email-Sender/.env:/var/www/.env
      - ./:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./database:/var/www/database
    command: php artisan queue:work
    networks:
      - smct-mailer
    environment:
      DB_CONNECTION: mysql
      DB_HOST: 172.17.0.1
      DB_PORT: 3306
      DB_DATABASE: smct-mailer
      DB_USERNAME: smct
      DB_PASSWORD: smct

  smct-mailer-nginx:
    image: nginx:alpine
    container_name: smct-mailer-nginx
    command: php artisan queue:work
    restart: unless-stopped
    ports:
      - 1008:1008
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www

    networks:
      - smct-mailer

networks:
  smct-mailer:
    driver: bridge
