services:
  smct-mailer:
    build:
      context: ./
      dockerfile: Dockerfile
    image: smct-mailer
    container_name: smct-mailer
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - /home/webserver/systems/testing/Multiple-Email-Sender/.env:/var/www/.env
      - ./:/var/www
      - ./docker-compose/nginx/default.conf:/etc/nginx/nginx.conf

    networks:
      - smct-mailer
    environment:
      DB_CONNECTION: sqlite

  smct-mailer-nginx:
    image: nginx:alpine
    container_name: smct-mailer-nginx
    restart: unless-stopped
    ports:
      - 1008:1008
    volumes:
      - ./default.conf:/etc/nginx/nginx.conf
      - ./:/var/www

    networks:
      - smct-mailer

networks:
  smct-mailer:
    driver: bridge
